prgrms-be-devcourse/NBE4-5-2-Team03

backend/src/main/java/com/example/Flicktionary/domain/review/controller/ReviewApiController.java, backend/src/main/java/com/example/Flicktionary/domain/review/dto/ReviewDto.java, backend/src/main/java/com/example/Flicktionary/domain/review/entity/Review.java, backend/src/main/java/com/example/Flicktionary/domain/review/repository/ReviewRepository.java, backend/src/main/java/com/example/Flicktionary/domain/review/service/ReviewService.java, backend/src/main/resources/application.yml, backend/src/test/java/com/example/Flicktionary/ReviewApplicationTest.java
review 엔티티, 서비스, 컨트롤러, tdd 등 기본적인 폴더와 파일 만들어 둠
=> feat Review

backend/src/main/java/com/example/Flicktionary/Series/controller/SeriesController.java, backend/src/main/java/com/example/Flicktionary/Series/domain/Series.java, backend/src/main/java/com/example/Flicktionary/Series/domain/SeriesStatus.java, backend/src/main/java/com/example/Flicktionary/Series/repository/SeriesRepository.java, backend/src/main/java/com/example/Flicktionary/Series/service/SeriesService.java
- Series Entity 구현
- ERD를 바탕으로 Series Entity 구현
=> [Series] 드라마 Entity 정의

backend/src/main/java/com/example/Flicktionary/Series/controller/SeriesController.java, backend/src/main/java/com/example/Flicktionary/Series/service/SeriesService.java, backend/src/main/java/com/example/Flicktionary/domain/actor/entity/Actor.java, backend/src/main/java/com/example/Flicktionary/domain/director/entity/Director.java, backend/src/main/java/com/example/Flicktionary/domain/favorite/controller/FavoriteController.java, backend/src/main/java/com/example/Flicktionary/domain/favorite/entity/ContentType.java, backend/src/main/java/com/example/Flicktionary/domain/favorite/entity/Favorite.java, backend/src/main/java/com/example/Flicktionary/domain/favorite/repository/FavoriteRepository.java, backend/src/main/java/com/example/Flicktionary/domain/favorite/service/FavoriteService.java, backend/src/main/java/com/example/Flicktionary/domain/genre/entity/Genre.java, backend/src/main/java/com/example/Flicktionary/domain/movie/entity/Movie.java, backend/src/main/java/com/example/Flicktionary/domain/review/entity/Review.java, backend/src/main/java/com/example/Flicktionary/domain/series/controller/SeriesController.java, backend/src/main/java/com/example/Flicktionary/domain/series/domain/Series.java, backend/src/main/java/com/example/Flicktionary/domain/series/domain/SeriesStatus.java, backend/src/main/java/com/example/Flicktionary/domain/series/repository/SeriesRepository.java, backend/src/main/java/com/example/Flicktionary/domain/series/service/SeriesService.java
=> feat: 영화 엔티티 구현

backend/src/main/java/com/example/Flicktionary/domain/favorite/entity/Favorite.java, backend/src/main/java/com/example/Flicktionary/domain/review/entity/Review.java, backend/src/main/java/com/example/Flicktionary/domain/user/entity/User.java, backend/src/main/java/com/example/Flicktionary/domain/user/entity/UserType.java
회원가입, 로그인, 가입정보 열람/수정 및 Spring Security와의 통합
회원 엔티티 구현
회원 리포지토리 선언
회원 서비스 구현
회원 컨트롤러 구현 및 엔드포인트 URI 설정
회원 엔티티와 Spring Security 통합 및 설정
예외 핸들러 구현
Closing this PR will close #18.
=> [회원] 기본 기능 구현

backend/src/main/java/com/example/Flicktionary/domain/review/controller/ReviewApiController.java, backend/src/main/java/com/example/Flicktionary/domain/review/controller/ReviewController.java, backend/src/main/java/com/example/Flicktionary/domain/review/dto/ReviewDto.java, backend/src/main/java/com/example/Flicktionary/domain/review/repository/ReviewRepository.java, backend/src/main/java/com/example/Flicktionary/domain/review/service/ReviewService.java, backend/src/test/java/com/example/Flicktionary/ReviewApplicationTest.java
리뷰에 대한 CRUD, Service, Controller, tdd를 구현했습니다.
아직 테스트를 하지 않아, 추후 수정할 수도 있습니다.
=> feat: CRUD, Service, Controller, tdd 구현

backend/src/main/java/com/example/Flicktionary/domain/movie/controller/MovieController.java, backend/src/main/java/com/example/Flicktionary/domain/movie/dto/MovieResponse.java, backend/src/main/java/com/example/Flicktionary/domain/movie/repository/MovieRepository.java, backend/src/main/java/com/example/Flicktionary/domain/movie/service/MovieService.java, backend/src/main/java/com/example/Flicktionary/global/dto/PageDto.java, backend/src/main/java/com/example/Flicktionary/global/init/BaseInitData.java, backend/src/test/java/com/example/Flicktionary/domain/movie/controller/MovieControllerTest.java, backend/src/test/java/com/example/Flicktionary/domain/movie/service/MovieServiceTest.java
- 페이징 처리
- 영화 제목으로 검색
- 정렬 기준에 따라 정렬 (id 오름차순, 평점 내림차순)
- 테스트 코드 작성
=> feat: 영화 목록 조회 구현

backend/src/main/java/com/example/Flicktionary/domain/movie/controller/MovieController.java, backend/src/main/java/com/example/Flicktionary/domain/movie/dto/MovieResponse.java, backend/src/main/java/com/example/Flicktionary/domain/movie/dto/MovieResponseWithDetail.java, backend/src/main/java/com/example/Flicktionary/domain/movie/entity/Movie.java, backend/src/main/java/com/example/Flicktionary/domain/movie/repository/MovieRepository.java, backend/src/main/java/com/example/Flicktionary/domain/movie/service/MovieService.java, backend/src/main/java/com/example/Flicktionary/domain/tmdb/service/TmdbService.java, backend/src/main/resources/application.yml, backend/src/test/java/com/example/Flicktionary/domain/movie/controller/MovieControllerTest.java, backend/src/test/java/com/example/Flicktionary/domain/movie/service/MovieServiceTest.java
- 리뷰 수 순으로 정렬 구현
- 검색 결과가 없으면 tmdb api를 통해 데이터를 가져오도록 수정
- 테스트 코드 수정
=> refactor: 영화 도메인 개선

backend/src/main/java/com/example/Flicktionary/domain/review/dto/ReviewDto.java, backend/src/main/java/com/example/Flicktionary/domain/review/entity/Review.java, backend/src/main/java/com/example/Flicktionary/domain/review/service/ReviewService.java, backend/src/test/java/com/example/Flicktionary/domain/review/ReviewApplicationTest.java
review 도메인의 user -> userAccount을 수정했습니다!
=> fix: user -> userAccount 수정

.gitignore, backend/src/main/java/com/example/Flicktionary/domain/series/dto/SeriesCastDto.java, backend/src/main/java/com/example/Flicktionary/domain/series/dto/SeriesDetailResponse.java, backend/src/main/java/com/example/Flicktionary/domain/series/dto/SeriesSummaryResponse.java, backend/src/main/java/com/example/Flicktionary/domain/series/entity/Series.java, backend/src/main/java/com/example/Flicktionary/domain/series/entity/SeriesCast.java, backend/src/main/java/com/example/Flicktionary/domain/series/repository/SeriesRepository.java, backend/src/main/java/com/example/Flicktionary/domain/series/service/SeriesService.java, backend/src/main/java/com/example/Flicktionary/domain/tmdb/dto/TmdbSeriesDetailResponse.java, backend/src/test/java/com/example/Flicktionary/domain/series/controller/SeriesControllerTest.java
- Series 상세 정보에서 배우, 감독의 프로필 사진과 배우의 배역 이름 추가 로직 구현
- Actor, Series의 중간 테이블인 SeriesCast 엔티티 구현
- Series 상세 정보 조회 기능에 배우, 감독의 프로필 사진과 배우의 배역 이름 추가 로직 구현
- 포스터 사진 W342, 인물 사진 W185로 크기 수정
- Series 목록 및 상세 조회 시 imageUrl -> posterPath로 이름 변경
=> [Series] 배우, 감독 사진 및 배역 이름 추가 구현

frontend/src/app/page.tsx
- 메인 페이지 구현
- 영화, 시리즈 검색창
- 평점 10 top 영화/시리즈 목록
=> feat: 메인 페이지 구현

backend/src/main/java/com/example/Flicktionary/domain/favorite/service/FavoriteService.java
정렬 도중 Movie와 Series가 섞이면서 발생하는 문제 수정
JPA 정렬의 문제로, comparator를 사용하여 정렬 후 반환
=> fix: 정렬문제 수정

backend/src/main/java/com/example/Flicktionary/domain/series/controller/SeriesController.java, backend/src/main/java/com/example/Flicktionary/domain/series/service/SeriesService.java, frontend/src/app/page.tsx, frontend/src/app/series/ClientPage.tsx, frontend/src/app/series/page.tsx
- Series 목록 조회 페이지 구현
- Series 목록 조회 페이지 구현
- SeriesController의 @RequestParam에 name 옵션 삭제(파라미터 전달 실패하는 오류 때문)
=> [Series] Series 목록 페이지 구현

frontend/src/app/page.tsx
화면 크기가 줄어들면 영화/시리즈 목록의 좌우 스크롤 버튼이 사라지던 문제를 해결했습니다.
=> refactor: 메인 페이지 수정

backend/src/main/java/com/example/Flicktionary/domain/movie/repository/MovieRepository.java, backend/src/main/java/com/example/Flicktionary/domain/movie/service/MovieService.java, frontend/src/app/movies/ClientPage.tsx
- 검색어의 대소문자와 띄어쓰기에 관계없이 검색이 되도록 수정
- 영화 목록 페이지에서 검색 결과가 없으면 "검색 결과가 없습니다" 라고 나오도록 수정
=> refactor: 검색 기능 수정

backend/src/main/java/com/example/Flicktionary/domain/movie/entity/Movie.java, backend/src/main/java/com/example/Flicktionary/domain/review/service/ReviewService.java, backend/src/test/java/com/example/Flicktionary/domain/review/controller/ReviewControllerTest.java, backend/src/test/java/com/example/Flicktionary/domain/review/service/ReviewServiceTest.java
- 리뷰 생성, 수정 삭제 시 영화, 시리즈의 averageRating과 ratingCount 정보를 수정하도록 구현했습니다.
- 해당 기능에 대한 테스트 코드를 추가했습니다.
=> refactor: 리뷰 생성, 수정, 삭제 시 영화, 시리즈 정보 업데이트

frontend/src/app/series/[id]/ClientPage.tsx, frontend/src/app/series/[id]/page.tsx, frontend/src/app/series/page.tsx
=> [Series] Series 상세 정보 페이지 구현

backend/src/main/java/com/example/Flicktionary/domain/actor/controller/ActorController.java, backend/src/main/java/com/example/Flicktionary/domain/actor/service/ActorService.java, backend/src/main/java/com/example/Flicktionary/domain/movie/repository/MovieCastRepository.java, frontend/src/app/actors/[actorId]/ClientPage.tsx, frontend/src/app/actors/[actorId]/page.tsx, frontend/src/app/movies/[id]/ClientPage.tsx
배우 정보 프론트 페이지 작성
- Movie Detail의 배우 정보에 링크 추가
- 배우 정보 페이지에서 출연한 영화 목록 확인
- 출연한 영화 페이지로 이동 기능
- 이전 페이지로 돌아가기
오전에 시작해서 오후에 끝날거라고는 생각도 못했네요 😂 
그 사이 시리즈 세부 페이지 추가되어서 출연한 시리즈 목록도 만들어야겠습니다!
=> [Actor] 배우 정보 FE

backend/src/main/java/com/example/Flicktionary/domain/actor/controller/ActorController.java, backend/src/main/java/com/example/Flicktionary/domain/actor/service/ActorService.java, backend/src/main/java/com/example/Flicktionary/domain/movie/repository/MovieCastRepository.java, backend/src/main/java/com/example/Flicktionary/domain/movie/service/MovieService.java, backend/src/main/java/com/example/Flicktionary/global/init/BaseInitData.java
- Actor 백엔드 작업
- movie detail data setting
- Create ActorController and GET
- Create ActorService
- add fetchMovieDetail on BaseInitData
=> [Actor] 배우 정보 BE

backend/src/main/java/com/example/Flicktionary/domain/favorite/controller/FavoriteController.java, backend/src/main/java/com/example/Flicktionary/domain/favorite/service/FavoriteService.java, frontend/src/app/my/favorites/ClientPage.tsx, frontend/src/app/my/favorites/page.tsx
- API URL 수정, 프론트 페이지 정상적으로 보이게 수정
- FavoriteController의 리턴 타입 수정
- delete 에외처리 추가
=> [Favorite] API URL 수정, 프론트 페이지 정상적으로 보이게 수정

backend/src/main/java/com/example/Flicktionary/domain/series/controller/SeriesController.java, backend/src/main/java/com/example/Flicktionary/domain/series/dto/SeriesSummaryResponse.java, backend/src/main/java/com/example/Flicktionary/domain/series/entity/Series.java, backend/src/main/java/com/example/Flicktionary/domain/series/service/SeriesService.java, backend/src/main/java/com/example/Flicktionary/domain/tmdb/dto/TmdbSeriesDetailResponse.java, backend/src/test/java/com/example/Flicktionary/domain/series/controller/SeriesControllerTest.java, backend/src/test/java/com/example/Flicktionary/domain/series/service/SeriesServiceTest.java, frontend/src/app/series/[id]/page.tsx
- Series<->TMDB 자동 업데이트 구현
- Series에 fetchDate를 추가해 7일이 지났을 때 해당 Series에 대한 상세 정보를 조회 할 경우 자동으로 TMDB정보를 받아 업데이트
- SeriesControllerTest에서 @WebMvcTest를 제거하고 @SpringBootTest, @AutoConfigureMockMvc 추가 (@WebMvcTest는 Controller 관련 Bean만 로드하는데 Security쪽 filter인지 뭔지가 로드가 안되서 나는 에러같음)
=> [Series] Series <-> TMDB 자동 업데이트 구현

backend/src/main/java/com/example/Flicktionary/domain/actor/controller/ActorController.java, backend/src/main/java/com/example/Flicktionary/domain/actor/service/ActorService.java, frontend/src/app/actors/[actorId]/ClientPage.tsx, frontend/src/app/series/ClientPage.tsx, frontend/src/app/series/[id]/ClientPage.tsx
배우 정보에 시리즈 정보 추가 BE / FE
- SeriesCastRepository 생성
- ActorService에 SeriesCast 조회 메서드 추가
- ActorController에 SeriesDTO 추가, SeriesCast 정보 전달
- /actors/[id]/ClientPage.tsx에 출연 시리즈 목록 추가
- /series/ClientPage.tsx 배우 정보 연동
- /series/ClientPage.tsx 시리즈 아이콘 수정
=> [Actor] 배우 정보에 시리즈 정보 추가

backend/src/main/java/com/example/Flicktionary/domain/series/repository/SeriesCastRepository.java
=> fix: 누락된 SeriesCastRepository 업로드

frontend/src/app/movies/[id]/ClientPage.tsx, frontend/src/components/review/ClientPage.tsx, frontend/src/components/review/ReviewForm.tsx
- 하은님이 만드신 리뷰 페이지를 컴포넌트 폴더로 이동시키고 영화 상세 페이지에서 사용하도록 했습니다.
- 영화 상세 페이지에서 평점과 리뷰 수 정보를 리뷰 컴포넌트로 내려줍니다.
- 리뷰 폼에서 리뷰 작성 후 평점과 리뷰 수를 업데이트하기 위해 영화 상세 페이지로 이동 (백에서 데이터 처리한 후 다시 그린다.) 
- 테스트 해보시고 이상없으면 app/reviews 디렉터리는 삭제해도 될 것 같습니다. (url로 review 페이지로 이동하면 에러가 발생할 수 있음)
- 평점과 리뷰 수는 영화 상세 페이지에서 내려주기 때문에 주석 처리된 평점을 가져오는 함수와 리뷰수 가져오는 함수는 삭제해도 될 것 같습니다. -> 테스트 해보시고 잘 작동하면 삭제하시면 되겠습니다.
- 현재 동일한 유저가 한 영화에 여러 번 리뷰를 남길 수 있는데 이것을 막아야 하는지 논의가 필요해 보입니다.
=> feature: 영화 상세 페이지에 리뷰 컴포넌트 추가

frontend/src/app/my/favorites/page.tsx, frontend/src/app/my/profile/page.tsx, frontend/src/lib/api/user.ts
로그인 된 유저에 따른 즐겨찾기 목록 조회하도록 수정하였습니다.
- /lib/api/user.ts 로 GET user api 분리, 재사용성 증가
- user.ts 이용하여 my/favorite 접속 시 로그인 된 유저의 즐겨찾기 목록 조회하도록 수정
- my/profile에서 user.ts 사용하도록 설정
유저 로그인 선행 작업이 끝나서 드디어 해결되었네요. 
리뷰 쪽도 user.ts 이용해서 진행하시면 될 것 같습니다.
=> [Favorite] 즐겨찾기 프론트 페이지 연결 수정

backend/src/main/java/com/example/Flicktionary/domain/review/service/ReviewService.java, backend/src/test/java/com/example/Flicktionary/domain/review/service/ReviewServiceTest.java, frontend/src/app/admin/reviews/page.tsx, frontend/src/app/my/favorites/page.tsx, frontend/src/app/my/profile/page.tsx
유저의 role이 'ADMIN'일 경우만 리뷰 관리자 페이지에 접속할 수 있게 구현했습니다!
tdd도 수정 및 전체 통과 시켰습니다.
=> [Review] 유저 role이 'ADMIN'일 경우만 리뷰 관리자 페이지에 접속할 수 있게 구현

frontend/src/app/ClientLayout.tsx, frontend/src/lib/hooks/useAuth.ts
유저 역할에 따른 버튼 변경, 상단에 유저 닉네임 정보 추가
=> [Admin] admin 접속 시 다른 화면 보이도록 수정

README.md, backend/build.gradle, backend/src/main/java/com/example/Flicktionary/global/service/EmailService.java, backend/src/main/resources/application.yml, backend/src/test/java/com/example/Flicktionary/global/service/EmailServiceTest.java
이메일 발송 기능
- 지메일 SMTP 서버를 통해 백엔드 서비스가 외부로 이메일을 전송할 수 있어야 한다.
- 받는이, 제목, 본문에 해당하는 문자열이 주어졌을때 그에 해당하는 이메일을 발송한다.
Closes #152.
=> [회원] 이메일 발송 기능 구현
